repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=5000']

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.7
    hooks:
      - id: clang-format
        types_or: [c++, c, header]

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format

  - repo: local
    hooks:
      - id: cppcheck
        name: cppcheck
        entry: cppcheck --enable=all --suppressions-list=.cppcheck_suppressions --error-exitcode=1 -I include/ src/ tests/
        language: system
        types: [c++]
        pass_filenames: false

      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy -p build --fix --quiet
        language: system
        files: \.(cc|cpp)$
        types_or: [c++]

      - id: lizard
        name: cyclomatic complexity (lizard)
        entry: lizard src tests -C 15 -Werror
        language: python
        additional_dependencies: [lizard]
        types: [c++]
        pass_filenames: false
